# 训练配置
train:
  total_timesteps: 1_000_000_000_000
  learning_rate: 0.004500352085918983
  n_steps: 4096
  batch_size: 1024
  n_epochs: 10
  gamma: 0.9618684267875346
  ent_coef: 0.013816254292753417
  n_envs: 24
  seed: 42
  device: "cpu"

# 环境配置
env:
  max_episode_steps: 10240
  t_fill: 510
  t_flat: 1300
  pulsed: true

logging:
  tensorboard_dir: tensorboard_logs
  log_interval: 1000

# 评估配置
evaluate:
  num_episodes: 10
  model_path: models/rf_control_model.zip